before_install:
  - ./bootstrap.sh
sudo: required
language: ruby
rvm:
 - "1.9.3"
 - "2.0"
 - "2.1"
 - "2.2"

script:
   - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && SPEC_ALL=true bundle exec rspec spec || true'
   - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] && SPEC_ALL=false bundle exec rspec spec || true'
