sudo: required
language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
gemfile:
  - gemfiles/Gemfile.rails-4.2.x
install:
  - "sudo pip install --upgrade pip"
  - "sudo pip install awsebcli --ignore-installed"

script:
   - "export EXCEPT_DEPLOYED=true"
   - "if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then export EXCEPT_DEPLOYED=false; fi"
   - "bundle exec rspec spec"
